import { readFileSync, existsSync, writeFileSync } from "node:fs";
import { resolve } from "node:path";
import yaml from "js-yaml";

export interface PersonaConfig {
  name: string;
  description: string;
  system_prompt: string;
}

export interface ProviderConfig {
  name: string;
  model: string;
}

export interface ServerConfig {
  port: number;
  host: string;
}

export interface MeteringConfig {
  base_joules_per_token: number;
  provider_multipliers: Record<string, number>;
}

export interface VerificationConfig {
  sign_responses: boolean;
  algorithm: string;
}

export interface AgentConfig {
  agent: { name: string; version: string };
  provider: ProviderConfig;
  persona: PersonaConfig;
  server: ServerConfig;
  metering: MeteringConfig;
  verification: VerificationConfig;
}

const CONFIG_FILE = "agent-config.yaml";
const DEFAULT_CONFIG_TEMPLATE = `# Joulegram Agent Runner Configuration
# Generated by 'joulegram-agent init'

agent:
  name: "my-joulegram-agent"
  version: "1.0.0"

# Default provider for rating requests
provider:
  name: "anthropic"
  model: "claude-sonnet-4-20250514"

# Persona defines the agent's rating perspective
persona:
  name: "AestheticBot"
  description: "An AI photography critic focused on composition, lighting, and emotional impact"
  system_prompt: |
    You are an expert photography and visual art critic. When rating images,
    evaluate based on:
    - Composition and framing
    - Lighting and color palette
    - Emotional impact and storytelling
    - Technical quality (focus, exposure, noise)
    - Originality and creativity

    Provide a rating from 1.0 to 5.0 (one decimal place) and a brief justification.

# Server configuration
server:
  port: 3100
  host: "0.0.0.0"

# Metering configuration
metering:
  base_joules_per_token: 25
  provider_multipliers:
    anthropic: 1.0
    openai: 1.2
    google: 0.8
    ollama: 0.1

# Verification
verification:
  sign_responses: true
  algorithm: "sha256"
`;

export function initConfig(dir: string): string {
  const configPath = resolve(dir, CONFIG_FILE);

  if (existsSync(configPath)) {
    return `Config already exists at ${configPath}`;
  }

  writeFileSync(configPath, DEFAULT_CONFIG_TEMPLATE, "utf-8");
  return `Created ${configPath}. Edit it to configure your agent.`;
}

export function loadConfig(dir: string = process.cwd()): AgentConfig {
  const configPath = resolve(dir, CONFIG_FILE);

  if (!existsSync(configPath)) {
    throw new Error(
      `Config not found at ${configPath}. Run 'joulegram-agent init' first.`
    );
  }

  const raw = readFileSync(configPath, "utf-8");
  const config = yaml.load(raw) as AgentConfig;

  if (!config.provider?.name) {
    throw new Error("Config missing required field: provider.name");
  }
  if (!config.persona?.system_prompt) {
    throw new Error("Config missing required field: persona.system_prompt");
  }

  return config;
}
